# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8797cf8307bbe9a6d57b48abad331621e83693ec61ef4088c3f82fc8aa24a66e29d5ec0f8ece2689ec55f0cfa7e649a827dad50b28a33408e7ee3d4fda50dce5

test:
  secret_key_base: 5a75733d91d625344cbae506f457a25d76224a13dbcf24ea94521f1430f43b4db8ab8a3a1a563df96a4585edfb82228eef9209218146b7f53ab00f3034ff2e06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
